{% set name = "onnx2pytorch" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/onnx2pytorch-{{ version }}.tar.gz
  sha256: 22ad0ce17fba8a996480ef816ead2ca4c1c66a6afd5e9bb5341a96d47c280ebf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch >=1.4.0 #Currently not avalaible for Windows
    - onnx >=1.6.0
    - torchvision >=0.9.0 #Currently not avalaible for Windows
    - __unix  # [unix]

test:
  imports:
    - onnx2pytorch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToriML/onnx2pytorch
  summary: Library to transform onnx model to pytorch.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    A library to transform ONNX model to PyTorch. This library enables use of PyTorch backend and all of its great features for manipulation of neural networks.

extra:
  recipe-maintainers:
    - HeavyTony2
